version: '3.9'
services:
  postgres:
    image: postgres:15-bullseye
    environment:
      POSTGRES_USER: datomic
      POSTGRES_PASSWORD: datomic
      POSTGRES_DB: datomic
    ports:
      - 5432:5432
    volumes:
      - ./files/init.sql:/docker-entrypoint-initdb.d/init.sql
      - datomic-storage-data:/var/lib/postgresql/data
    networks:
      - datomic-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "datomic"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  memcached:
    image: memcached:1.6-bullseye
    ports:
      - 11211:11211
    networks:
      - datomic-network
    restart: always
    depends_on:
      postgres:
        condition: service_started

  transactor:
    image: datomic:1.0.6735-java17 
    build: 
      context: ./images/datomic/
      dockerfile: Dockerfile
      args:
        DATOMIC_CONFIG: /opt/datomic/config/sql-transactor.properties 
    ports:
      - 4334:4334
    volumes:
      - ./files/sql-transactor.properties:/opt/datomic/config/sql-transactor.properties
      - datomic-transactor-logs:/opt/datomic/logs
    networks:
      - datomic-network
    healthcheck:
      test: ["CMD", "curl", "http://localhost:9999/health"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
    restart: always
    entrypoint: /opt/datomic/bin/transactor -Xmx4g -Xms4g /opt/datomic/config/sql-transactor.properties
    depends_on:
      postgres:
        condition: service_healthy
      memcached:
        condition: service_started

  datomic-db-init:
    image: datomic:1.0.6735-java17 
    volumes:
      - ./files/db-init.clj:/opt/datomic/db-init.clj
    networks:
      - datomic-network
    restart: on-failure:1
    entrypoint: /opt/datomic/bin/run /opt/datomic/db-init.clj
    depends_on:
      transactor:
        condition: service_healthy

  peer-server:
    image: datomic:1.0.6735-java17 
    ports:
      - 8998:8998
    volumes:
      - ./files/peer-server.sh:/opt/datomic/peer-server.sh
    networks:
      - datomic-network
    restart: always
    entrypoint: bash /opt/datomic/peer-server.sh
    depends_on:
      datomic-db-init:
        condition: service_completed_successfully

  console:
    image: datomic:1.0.6735-java17 
    ports:
      - 8080:8080
    networks:
      - datomic-network
    restart: always
    entrypoint: /opt/datomic/bin/console -p 8080 sql 'datomic:sql://?jdbc:postgresql://postgres:5432/datomic?user=datomic&password=datomic'
    depends_on:
      datomic-db-init:
        condition: service_completed_successfully

networks:
  datomic-network:
    driver: bridge

volumes:
  datomic-storage-data:
  datomic-transactor-logs:
